[workspace]
resolver = "3"
members = [
    "API",
    "CLI",
    "core",
    "MCP",
    "GUI/src-tauri",
    "tests",
    "FFI"]

package.version = "0.12.2"
package.edition = "2021"

[profile.release]
opt-level = 3
lto = "thin"

